permalink: pretty
theme: jekyll_patternbot

patternbot:
  title: "Black Market"
  description: |
    You need something specific? You want it in black? You're at the good place. The Black Market sells all kind of different black items, from geek loot to dark witchcraft material.
  font_url: "https://fonts.googleapis.com/css?family=Noto+Sans:400,700|Noto+Serif:400,700&display=swap"
  colors:
    background: "--color-primary-dark"
    accent: "--color-secondary-light-grey"
  rationales:
    typefaces.primary: |
      Abril was selected because
    typefaces.secondary: |
      Noto is used for
    colors.primary: |
      The primary colours are
    colors.secondary: |
      The secondary colours are
  layouts:
    default: |
      The default layout should be used for almost every page, this is including the website’s main header and footer.
