permalink: pretty
theme: jekyll_patternbot

patternbot:
  title: "Black Market"
  description: |
    You need something specific? You want it in black? You're at the good place. The Black Market sells all kind of different black items, from geek loot to dark witchcraft material.
  font_url: "https://fonts.googleapis.com/css?family=Noto+Sans:400,700|Noto+Serif:400,700&display=swap"
  colors:
    background: "--color-primary-dark"
    accent: "--color-secondary-light-grey"
  rationales:
    typefaces.primary: |
      Noto Serif was selected for its readability and nice contrasting form when reversed. This serif typeface is elegant and clean. Noto Serif is to be used for all text, but mostly Headings.
    typefaces.secondary: |
      Noto Sans is used for the same reason its Serif brother was choosen. It should be use for body copy or contrasting sub-headings.
    colors.primary: |
      The primary colours are the dark tones; this isn't called the Black Market for no reason. They should be used mostly for backgrounds, and for the text when contrast is required.
    colors.secondary: |
      The secondary colours are the primary's opposite. They should be use for text on darker background, or for cards and forms.
    colors.accent: |
      The accent colours are the only vibrant and bright touch on the website, and should be used for buttons and in some hover situations.
  layouts:
    default: |
      The default layout should be used for almost every page, this is including the website’s main header and footer.
collections:
  products:
    output: true
defaults:
  - scope:
      path: _products
    values:
      layout: product
