title: "Cards"
description: |
  Cards are blae ble blou

patterns:
  products:
    title: "Product Card"
    description: |
      Products card are the
  # banner:
  #   title: "Banner"
  #   description: |
  #     bla ble blou
