title: "Banners"
description: |
    Banners should be used to separate
patterns:
  top-banner:
    title: "Top Banner"
    description: |
      The top banner is used on the main page only. It is the first description of the page, welcoming the users.
  call-to-action:
    title: "Call to action Banner"
    description: |
      The call to action banner is used on the main page only. It is meant to showcase new arrlivals, sales, and the top selling products.
  promotional-banner:
    title: "Promotional Banner"
    description: |
      The promotional banner is used to promote wide sales and new items on the website.
